import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type ThemeMode = 'system' | 'light' | 'dark'
export type LanguageMode = 'system' | 'zh' | 'en'
export type EffectiveLanguage = 'zh' | 'en'

type Variables = Record<string, string | number>

interface PreferencesValue {
  theme: ThemeMode
  effectiveTheme: 'light' | 'dark'
  language: LanguageMode
  effectiveLanguage: EffectiveLanguage
  locale: string
  setTheme: (theme: ThemeMode) => void
  setLanguage: (language: LanguageMode) => void
  t: (key: string, variables?: Variables) => string
}

const messages: Record<EffectiveLanguage, Record<string, string>> = {
  zh: {
    'common.add': '添加', 'common.cancel': '取消', 'common.save': '保存', 'common.close': '关闭',
    'common.search': '搜索', 'common.edit': '编辑', 'common.delete': '移除', 'common.refresh': '刷新',
    'common.online': '在线', 'common.offline': '离线', 'common.pending': '待连接', 'common.revoked': '已撤销',
    'common.valid': '有效', 'common.expiring': '即将到期', 'common.expired': '已到期', 'common.none': '无',
    'common.days': '{count} 天', 'common.items': '{count} 项', 'common.nodes': '{count} 个节点',
    'common.loading': '加载中…', 'common.saving': '保存中…', 'common.queueing': '提交中…',
    'common.noResults': '没有匹配结果', 'common.optional': '可选', 'common.select': '请选择',
    'common.system': '系统', 'common.light': '浅色', 'common.dark': '深色', 'common.chinese': '中文', 'common.english': 'English',
    'nav.overview': '概览', 'nav.domains': '域名', 'nav.domainsShort': '域名', 'nav.certificates': '证书',
    'nav.nodes': '节点', 'nav.accounts': '账户', 'nav.pending': '待处理', 'nav.audit': '日志', 'nav.settings': '设置',
    'nav.main': '主导航', 'nav.mobile': '移动导航', 'nav.open': '打开菜单', 'nav.close': '关闭菜单',
    'app.allHealthy': '全部正常', 'app.waitingNode': '等待首个节点', 'app.needsAttention': '需要检查',
    'app.configVerified': '配置已验证', 'app.statusSynced': '状态已同步', 'app.refreshNow': '刷新',
    'app.language': '语言', 'app.theme': '主题', 'app.admin': '管理员', 'app.logout': '退出',
    'page.kickerStatus': '状态', 'page.kickerControl': '控制台',
    'login.eyebrow': 'NGINX ATLAS', 'login.title': '管理域名与证书',
    'login.description': '统一管理节点路由与 TLS。变更前会先跑 nginx -t。',
    'login.cardTitle': '登录', 'login.cardDescription': '使用安装时设置的管理员密码。',
    'login.password': '密码', 'login.passwordPlaceholder': '管理员密码', 'login.submit': '登录',
    'login.submitting': '验证中…', 'login.secure': '会话令牌仅保存在本浏览器，密码不会落盘。',
    'login.tooShort': '密码至少 12 个字符。', 'login.invalid': '密码错误，或主控暂时不可用。', 'login.configUnavailable': '暂时无法读取登录设置。', 'login.challengeUnavailable': '安全验证暂时不可用。',
    'overview.title': '运行总览', 'overview.description': '节点、域名、证书与最近变更。',
    'overview.nodesOnline': '节点', 'overview.allNormal': '全部在线', 'overview.checkNeeded': '有异常',
    'overview.certRisk': '临期证书', 'overview.within30': '30 天内', 'overview.noRisk': '暂无风险',
    'overview.routes': '域名', 'overview.searchDomain': '搜索域名', 'overview.noDomain': '暂无域名',
    'overview.noDomainDescription': '添加第一条路由后会出现在这里。', 'overview.adjustSearch': '试试其他关键词。',
    'overview.total': '共 {count} 条', 'overview.viewAll': '全部', 'overview.timeline': '证书到期',
    'overview.next90': '近 90 天', 'overview.nodeHealth': '节点', 'overview.activity': '最近活动', 'overview.pending': '待处理',
    'overview.noActivity': '暂无活动', 'overview.noActivityDescription': '部署与续期记录会显示在这里。',
    'overview.noCertificates': '暂无证书', 'overview.noCertificatesDescription': '签发或上传后显示到期情况。',
    'overview.viewCertificates': '证书', 'overview.noNodes': '暂无节点', 'overview.noNodesDescription': '生成添加命令并在 VPS 上执行。',
    'overview.viewNodes': '节点', 'overview.waitingReport': '等待上报', 'overview.nginxUndetected': '未检测',
    'overview.nginxOk': 'Nginx 正常', 'overview.nginxBad': 'Nginx 异常',
    'overview.quickActions': '快捷操作', 'overview.activeRoutes': '运行域名', 'overview.autoRenewCerts': '自动续期',
    'overview.expiringDomains': '到期提醒', 'overview.commands': '安装与卸载',
    'overview.installNode': '安装节点', 'overview.uninstallNode': '卸载节点', 'overview.uninstallController': '卸载主控',
    'overview.uninstallControllerWarning': '将移除主控与本机代理，现有 Nginx 配置和证书保留。',
    'domain.title': '域名', 'domain.description': '把域名指到节点上的上游地址与端口。',
    'domain.add': '添加', 'domain.editTitle': '编辑域名', 'domain.updateSubmit': '保存', 'domain.searchPlaceholder': '搜索域名', 'domain.managedTab': '已管理',
    'domain.discoveredTab': '发现', 'domain.discoveredTitle': '节点上的现有站点',
    'domain.discoveredDescription': '可先监控，或备份后由 Atlas 接管配置。',
    'domain.adopt': '监控', 'domain.adopted': '已管理', 'domain.noDiscovered': '没有新站点',
    'domain.noDiscoveredDescription': '节点下次心跳时会同步 server_name。',
    'domain.empty': '还没有域名', 'domain.emptyDescription': '创建后会先验证再重载 Nginx。',
    'domain.columnDomain': '域名', 'domain.columnRoute': '上游', 'domain.columnCert': '证书',
    'domain.columnNode': '节点', 'domain.columnState': '状态', 'domain.localConfig': '仅监控',
    'domain.takenOverBadge': '已接管', 'domain.managedConfig': 'Atlas', 'domain.configPath': '配置', 'domain.tls': 'TLS', 'domain.http': 'HTTP',
    'domain.showing': '{shown}/{total}', 'domain.transactionNote': '',
    'domain.discoveredFooter': '来自 nginx -T',
    'domain.removeTitle': '移除域名配置？', 'domain.removeObservedTitle': '停止管理这个域名？',
    'domain.removeDescription': '节点将删除 {domain} 的托管配置，通过 nginx -t 后才会重载。证书文件不会自动删除。',
    'domain.removeObservedDescription': '只会从 Atlas 管理列表移除 {domain}，节点原有 Nginx 配置不会修改。',
    'domain.removeTakenOverTitle': '停止接管并恢复原规则？',
    'domain.removeTakenOverDescription': '节点将移除 {domain} 的 Atlas 配置、恢复接管前的 Nginx 规则，并在 nginx -t 通过后重载。证书不会删除。',
    'domain.removeAction': '移除域名', 'domain.stopManaging': '停止管理', 'domain.restoreOriginal': '恢复原规则',
    'domain.runtimeQueued': '排队', 'domain.runtimeRunning': '部署中', 'domain.runtimeFailed': '失败',
    'domain.runtimeActive': '运行中', 'domain.runtimePending': '待部署', 'domain.unconnected': '未连接',
    'domain.certPending': '待证书', 'domain.httpOnlyShort': 'HTTP',
    'domain.drawerKicker': '新路由', 'domain.drawerSubtitle': '', 'domain.stepRoute': '路由', 'domain.stepCertificate': '证书', 'domain.stepDeploy': '部署',
    'domain.targetNode': '节点', 'domain.upstreamHost': '上游', 'domain.projectPort': '端口', 'domain.certificateSource': '证书',
    'domain.existingCertificate': '已有证书', 'domain.uploadCertificate': '上传', 'domain.letsencrypt': "Let's Encrypt", 'domain.letsencryptShort': 'ACME',
    'domain.certificateLocation': '证书', 'domain.localCertificate': '节点 /etc/ssl/{domain}', 'domain.currentNodeCertificate': '当前节点证书', 'domain.controllerCertificate': '{domain} · {days} 天',
    'domain.syncOthers': '同步到其他节点', 'domain.noOtherNodes': '暂无其他节点', 'domain.syncDescription': '部署后把证书推到所选节点并重载。',
    'domain.preview': '配置预览', 'domain.httpOnly': '仅 HTTP，暂不启用 TLS',
    'domain.deployProof': '',
    'domain.offlineWarning': '节点离线，任务会排队等待上线。', 'domain.submit': '部署',
    'domain.validation': '请完整填写有效域名、目标节点、上游地址和端口。',
    'domain.validationFiles': '请同时选择 fullchain.pem 与 privkey.pem。', 'domain.validationAccounts': '自动签发或续期需要 DNS 与 ACME 账户。',
    'certificate.title': '证书', 'certificate.description': '签发、续期，并同步到节点。',
    'certificate.add': '添加', 'certificate.total': '证书', 'certificate.expiringCount': '临期',
    'certificate.autoRenewCount': '自动续期', 'certificate.nodeCopies': '副本', 'certificate.syncedNodes': '已同步节点',
    'certificate.searchPlaceholder': '搜索域名', 'certificate.allStatuses': '全部',
    'certificate.validOnly': '有效', 'certificate.expiringOnly': '临期/过期', 'certificate.empty': '还没有证书',
    'certificate.emptyDescription': '上传、ACME 签发，或从节点导入。',
    'certificate.sourceACME': 'ACME', 'certificate.sourceUpload': '上传', 'certificate.sourceLocal': '节点',
    'certificate.expiry': '到期', 'certificate.source': '来源', 'certificate.autoRenew': '自动续期',
    'certificate.distribution': '分发', 'certificate.renew': '申请', 'certificate.sync': '同步',
    'certificate.enabled': '自动续期开', 'certificate.disabled': '自动续期关', 'certificate.remaining': '{count} 天',
    'certificate.enableAutoRenew': '启用 {domain} 自动续期', 'certificate.disableAutoRenew': '关闭 {domain} 自动续期',
    'certificate.automationUnavailable': '请先配置签发节点和证书账户。',
    'certificate.renewConfirmTitle': '申请新证书？', 'certificate.renewConfirmDescription': '{domain} 将通过 DNS-01 重新申请证书，成功后写入目标节点并验证 Nginx。', 'certificate.renewConfirmAction': '确认申请',
    'certificate.fingerprint': 'SHA-256 指纹', 'certificate.modeUpload': '上传证书',
    'certificate.modeUploadShort': '上传', 'certificate.modeIssue': '申请证书', 'certificate.modeIssueShort': '申请',
    'certificate.modeImport': '节点证书', 'certificate.modeImportShort': '节点',
    'certificate.modeUploadHint': '', 'certificate.modeIssueHint': '',
    'certificate.modeImportHint': '', 'certificate.domain': '证书域名',
    'certificate.signingNode': '签发节点', 'certificate.sourceNode': '来源节点', 'certificate.nodeCertificate': '节点证书',
    'certificate.dnsAccount': 'DNS 账户', 'certificate.acmeAccount': 'ACME 账户',
    'certificate.syncNodes': '自动同步节点', 'certificate.syncHint': '',
    'certificate.renewToggle': '到期前自动续期', 'certificate.renewHint': '进入 {days} 天到期窗口后自动执行 DNS-01。',
    'certificate.fullchain': '证书文件', 'certificate.privkey': '私钥文件', 'certificate.certificateFile': '证书文件', 'certificate.privateKeyFile': '私钥文件', 'certificate.chooseFile': '选择文件', 'certificate.detectDomain': '自动识别域名并规范保存',
    'certificate.submitUpload': '验证并添加', 'certificate.submitIssue': '申请证书', 'certificate.submitImport': '接管证书',
    'certificate.noNodeCertificates': '该节点没有上报可接管的有效证书。',
    'certificate.validationDomain': '请输入有效的证书域名。', 'certificate.validationFiles': '请选择证书与私钥文件。',
    'certificate.validationNode': '请选择可用节点。', 'certificate.validationAccounts': '请选择 DNS 与 ACME 账户。',
    'nodes.title': '节点', 'nodes.description': '节点出站连接主控，无需额外管理端口。',
    'nodes.add': '添加', 'nodes.empty': '还没有节点', 'nodes.emptyDescription': '安装命令位于概览。',
    'nodes.command': '生成命令', 'nodes.hostnamePending': '等待主机名', 'nodes.addresses': '地址',
    'nodes.nginx': 'Nginx', 'nodes.platform': '平台', 'nodes.certDirectory': '证书目录', 'nodes.certFound': '{count} 个已发现',
    'nodes.siteFound': '{count} 个域名', 'nodes.lastSeen': '最后在线：{time}', 'nodes.never': '从未连接',
    'nodes.revoke': '撤销节点', 'nodes.revokeTitle': '撤销节点访问？',
    'nodes.revokeDescription': '{node} 将无法继续领取任务。节点本地现有 Nginx 配置与证书不会被删除。',
    'accounts.title': '账户', 'accounts.description': 'DNS 与 ACME 凭据加密保存。',
    'accounts.dnsTitle': 'DNS 账户', 'accounts.acmeTitle': 'ACME 账户', 'accounts.addDNS': '添加 DNS 账户',
    'accounts.addACME': '添加 ACME 账户', 'accounts.emptyDNS': '尚未配置 DNS', 'accounts.emptyDNSDescription': '添加 lego 支持的 DNS 提供商和最小权限 API 凭据。',
    'accounts.emptyACME': '尚未配置 ACME', 'accounts.emptyACMEDescription': '保存邮箱、目录地址以及可选的 EAB 信息。',
    'accounts.credentials': '{count} 项凭据', 'accounts.eab': '已配置 EAB', 'accounts.standard': '标准账户',
    'accounts.encrypted': 'AES-256-GCM 加密', 'accounts.editDNS': '编辑 DNS 账户', 'accounts.editACME': '编辑 ACME 账户',
    'audit.title': '日志', 'audit.description': '系统事件与操作记录。',
    'audit.event': '事件', 'audit.target': '对象', 'audit.time': '时间', 'audit.level': '级别', 'audit.controller': '主控',
    'audit.success': '成功', 'audit.warning': '警告', 'audit.error': '错误', 'audit.info': '信息',
    'audit.empty': '暂无审计记录', 'audit.emptyDescription': '完成一次配置操作后会出现在这里。',
    'pending.title': '待处理', 'pending.description': '', 'pending.empty': '没有待处理任务',
    'pending.queued': '排队', 'pending.running': '执行中', 'pending.failed': '失败', 'pending.reason': '失败原因', 'pending.noReason': '未返回失败原因', 'pending.retry': '重试',
    'pending.applyDomain': '部署域名', 'pending.deleteDomain': '移除域名', 'pending.syncCertificate': '同步证书', 'pending.issueCertificate': '申请证书',
    'pending.captureCertificate': '接管证书', 'pending.reloadNginx': '重载 Nginx', 'pending.updateAtlas': '更新 Atlas', 'pending.updateSystem': '更新系统',
    'settings.title': '设置', 'settings.description': '账户、节点状态与访问。',
    'settings.certificateAccounts': '证书账户', 'settings.cloudflareToken': 'Cloudflare API 密钥', 'settings.acmeEmail': 'ACME 邮箱',
    'settings.configured': '已配置', 'settings.notConfigured': '未配置', 'settings.nodeStatus': '节点状态',
    'settings.nodePollFrequency': '获取频率', 'settings.seconds': '{count} 秒',
    'settings.appearance': '外观与语言', 'settings.theme': '颜色模式', 'settings.language': '界面语言',
    'settings.security': '证书安全', 'settings.securityDescription': '',
    'settings.transport': '节点通信', 'settings.transportDescription': '',
    'settings.transaction': 'Nginx 事务', 'settings.transactionDescription': '',
    'settings.atomic': '原子回滚', 'settings.password': '管理员密码', 'settings.passwordDescription': '',
    'settings.changePassword': '更改密码', 'settings.logout': '退出当前管理员会话',
    'settings.accessProtection': '访问保护', 'settings.enabled': '已开启', 'settings.disabled': '未开启',
    'settings.ipAllowlist': '面板 IP 白名单', 'settings.ruleCount': '{count} 条规则', 'settings.currentIP': '当前 IP：{ip}',
    'settings.keepSecret': '保留当前密钥', 'settings.turnstileCredentialsRequired': '请填写 Site Key 与 Secret Key。',
    'dialog.nodeTitle': '添加 Linux 节点', 'dialog.nodeDescription': '接入时自动使用主机名。',
    'dialog.nodeName': '节点名称', 'dialog.nodeNamePlaceholder': 'nanami-sakura', 'dialog.generate': '生成命令',
    'dialog.commandReady': '节点命令已就绪', 'dialog.copyCommand': '复制命令', 'dialog.copied': '已复制',
    'dialog.commandHint': '命令包含短期注册令牌，请勿发送到公开日志。',
    'dialog.dnsAddTitle': '添加 DNS 账户', 'dialog.dnsEditTitle': '编辑 DNS 账户',
    'dialog.dnsDescription': '使用最小权限的 Zone DNS 编辑令牌。',
    'dialog.accountName': '账户名称', 'dialog.provider': 'lego 提供商', 'dialog.credentials': '环境变量凭据',
    'dialog.addCredential': '增加', 'dialog.keepCredentials': '保留当前加密凭据', 'dialog.replaceCredentials': '替换凭据',
    'dialog.credentialName': '凭据变量 {index}', 'dialog.credentialValue': '凭据值 {index}', 'dialog.removeCredential': '移除此项',
    'dialog.credentialHint': 'API 列表只返回变量名，凭据值不会回传到浏览器。',
    'dialog.acmeAddTitle': '添加 ACME 账户', 'dialog.acmeEditTitle': '编辑 ACME 账户',
    'dialog.acmeDescription': '',
    'dialog.email': '联系邮箱', 'dialog.directory': 'ACME 目录', 'dialog.eab': '外部账户绑定（EAB）',
    'dialog.keepEAB': '保留现有 EAB 密钥', 'dialog.clearEAB': '清除 EAB', 'dialog.eabKID': 'EAB KID', 'dialog.eabHMAC': 'EAB HMAC',
    'dialog.syncTitle': '同步证书', 'dialog.syncDescription': '将 {domain} 的当前证书版本安全推送到其他节点。',
    'dialog.syncOnline': '在线，任务将立即领取', 'dialog.syncOffline': '离线，任务会保持排队',
    'dialog.syncProof': '',
    'dialog.syncAction': '同步到 {count} 个节点', 'dialog.passwordTitle': '更改管理员密码',
    'dialog.passwordDescription': '保存后其他会话立即失效，当前浏览器会自动换取新会话。',
    'dialog.currentPassword': '当前密码', 'dialog.newPassword': '新密码', 'dialog.confirmPassword': '确认新密码',
    'dialog.passwordRule': '至少 12 个字符，建议使用密码管理器生成。', 'dialog.passwordMismatch': '两次输入的新密码不一致。',
    'dialog.changePassword': '更改密码', 'dialog.remove': '移除',
    'settings.quickPreferences': '外观与语言',
    'domain.routeHint': '', 'domain.certificateHint': '',
    'domain.validationCertificate': '请选择一张覆盖该域名的已有证书。', 'domain.validationCloudflare': '请选择可用于编辑区域 DNS 的 Cloudflare 账户。',
    'domain.noMatchingCertificate': '没有覆盖该域名的证书', 'domain.cloudflareTitle': '同步 Cloudflare DNS',
    'domain.cloudflareHint': '', 'domain.cloudflareAccount': 'Cloudflare 账户',
    'domain.recordContent': '记录内容', 'domain.recordAuto': '自动使用节点 IP', 'domain.proxyMode': '代理状态',
    'domain.orangeCloud': '代理', 'domain.grayCloud': 'DNS', 'domain.observe': '监控', 'domain.takeover': '接管',
    'domain.takeoverUnavailable': '需要可用上游、支持的配置路径，以及覆盖该域名的证书。',
    'domain.nginxSettings': 'Nginx 高级设置', 'domain.nginxSettingsHint': '',
    'domain.nginxWebsocket': '支持 WebSocket', 'domain.nginxWebsocketHint': '',
    'domain.nginxHttp2': 'HTTP/2 协议', 'domain.nginxHttp2Hint': '',
    'domain.nginxGzip': '开启 Gzip 压缩', 'domain.nginxGzipHint': '',
    'domain.takeoverConfirmTitle': '接管此站点？', 'domain.takeoverConfirmDescription': '会备份 {path}，再为 {domain} 写入 Atlas 规则；nginx -t 失败会自动恢复。',
    'domain.takeoverConfirmAction': '确认接管',
    'certificate.additionalNames': '证书覆盖域名', 'certificate.additionalNamesHint': '按 Enter 或逗号添加，支持 *.example.com；单张证书最多 20 个名称。',
    'certificate.validationAutomation': '请选择签发节点，并设置 7–60 天的续期窗口。',
    'certificate.editAutomation': '编辑签发与续期', 'certificate.editAutomationHint': '',
    'certificate.renewDays': '到期前续期（天）', 'certificate.namesCount': '{count} 个域名',
    'nodes.manage': '管理', 'nodes.manageTitle': '{node}', 'nodes.manageDescription': '名称、版本与系统更新。',
    'nodes.controller': '主控', 'nodes.manageControllerDescription': '更新主控与本机代理后会重启相关服务。',
    'nodes.rename': '节点显示名称', 'nodes.atlasRelease': 'Nginx Atlas 发行版', 'nodes.controllerRelease': '主控与本机代理', 'nodes.versionPair': '当前 {current} · 最新 {latest}',
    'nodes.checkUpdate': '检查更新', 'nodes.updateAvailable': '可更新至 {version}', 'nodes.upToDate': '已是最新发行版',
    'nodes.updateAtlas': '更新 Atlas', 'nodes.confirmUpdate': '确认更新', 'nodes.systemUpdate': 'APT 与 Nginx 更新',
    'nodes.systemUpdateHint': '执行 apt update / upgrade，保留现有配置，再验证并重载 Nginx。', 'nodes.systemUpdateUnsupported': '当前仅支持基于 APT 的节点。',
    'nodes.updatePackages': '更新软件包', 'nodes.confirmSystemUpdate': '确认系统更新', 'nodes.uninstallTitle': '卸载节点代理',
    'nodes.uninstallHint': '命令只移除本项目的节点代理；Nginx、站点配置和 /etc/ssl 证书均会保留。', 'nodes.copyUninstall': '复制卸载命令',
    'nodes.reinstallTitle': '再次获取安装命令', 'nodes.reinstallHint': '在目标 Linux VPS 上执行此命令以接入或重新接入本主控。',
    'nodes.generateInstallCommand': '获取安装命令', 'nodes.copyInstall': '复制安装命令',
    'toast.domainQueued': '域名已加入部署队列；节点将先验证 Nginx 配置。',
    'toast.domainObserved': '已加入节点现有域名管理；原 Nginx 配置未修改。', 'toast.domainRemoved': '域名移除任务已排队。',
    'toast.observationRemoved': '已停止管理节点现有域名，原配置未修改。', 'toast.nodeRevoked': '节点凭据已撤销。',
    'toast.dnsSaved': 'DNS 账户已安全保存。', 'toast.acmeSaved': 'ACME 账户已保存。',
    'toast.certQueued': '证书任务已加入队列。', 'toast.certUploaded': '证书已验证并加入管理。',
    'toast.renewQueued': '{domain} 已加入证书申请队列。', 'toast.autoRenewEnabled': '{domain} 已开启自动续期。', 'toast.autoRenewDisabled': '{domain} 已关闭自动续期。', 'toast.syncQueued': '证书已加入 {count} 个节点的同步队列。',
    'toast.passwordChanged': '管理员密码已更改，其他会话已撤销。',
    'toast.domainTakeoverQueued': '现有 Nginx 规则已加入安全接管队列。', 'toast.certificateAutomationSaved': '证书签发与续期设置已保存。',
    'toast.releaseChecked': '已读取最新 GitHub 发行版。', 'toast.nodeRenamed': '节点名称已更新。',
    'toast.atlasUpdateQueued': 'Atlas 更新任务已加入节点队列。', 'toast.systemUpdateQueued': 'APT 与 Nginx 更新任务已加入节点队列。',
    'toast.pollFrequencySaved': '节点状态频率已更新。', 'toast.accessSettingsSaved': '访问保护已保存。', 'toast.jobRetried': '任务已重新排队。',
    'error.dashboard': '无法读取主控状态', 'error.domain': '无法创建域名', 'error.adopt': '无法接管节点域名',
    'error.node': '无法生成节点命令', 'error.dns': '无法保存 DNS 账户', 'error.acme': '无法保存 ACME 账户',
    'error.certificate': '无法创建证书任务', 'error.password': '无法更改管理员密码',
    'error.removeDomain': '无法移除域名', 'error.revokeNode': '无法撤销节点', 'error.renew': '无法创建续期任务', 'error.autoRenew': '无法更改自动续期', 'error.sync': '无法创建同步任务',
    'error.takeover': '无法接管现有 Nginx 规则', 'error.certificateAutomation': '无法保存证书自动化设置',
    'error.release': '无法检查 GitHub 发行版', 'error.uninstallCommand': '无法生成卸载命令', 'error.renameNode': '无法更改节点名称',
    'error.atlasUpdate': '无法创建 Atlas 更新任务', 'error.systemUpdate': '无法创建系统更新任务', 'error.settings': '无法保存设置', 'error.retryJob': '无法重试任务',
    'update.kicker': '主控更新', 'update.title': '正在更新', 'update.complete': '更新完成', 'update.failed': '更新失败',
    'update.prepare': '准备', 'update.install': '安装', 'update.restart': '重启', 'update.refreshing': '正在刷新页面…',
  },
  en: {
    'common.add': 'Add', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.close': 'Close',
    'common.search': 'Search', 'common.edit': 'Edit', 'common.delete': 'Remove', 'common.refresh': 'Refresh',
    'common.online': 'Online', 'common.offline': 'Offline', 'common.pending': 'Pending', 'common.revoked': 'Revoked',
    'common.valid': 'Valid', 'common.expiring': 'Expiring soon', 'common.expired': 'Expired', 'common.none': 'None',
    'common.days': '{count} days', 'common.items': '{count} items', 'common.nodes': '{count} nodes',
    'common.loading': 'Loading…', 'common.saving': 'Saving…', 'common.queueing': 'Submitting…',
    'common.noResults': 'No matching results', 'common.optional': 'Optional', 'common.select': 'Select',
    'common.system': 'System', 'common.light': 'Light', 'common.dark': 'Dark', 'common.chinese': '中文', 'common.english': 'English',
    'nav.overview': 'Overview', 'nav.domains': 'Domains', 'nav.domainsShort': 'Domains', 'nav.certificates': 'Certs',
    'nav.nodes': 'Nodes', 'nav.accounts': 'Accounts', 'nav.pending': 'Pending', 'nav.audit': 'Logs', 'nav.settings': 'Settings',
    'nav.main': 'Main navigation', 'nav.mobile': 'Mobile navigation', 'nav.open': 'Open menu', 'nav.close': 'Close menu',
    'app.allHealthy': 'All healthy', 'app.waitingNode': 'Waiting for first node', 'app.needsAttention': 'Needs attention',
    'app.configVerified': 'Config verified', 'app.statusSynced': 'Status synced', 'app.refreshNow': 'Refresh',
    'app.language': 'Language', 'app.theme': 'Theme', 'app.admin': 'Admin', 'app.logout': 'Sign out',
    'page.kickerStatus': 'Status', 'page.kickerControl': 'Console',
    'login.eyebrow': 'NGINX ATLAS', 'login.title': 'Domains & certificates',
    'login.description': 'Manage routes and TLS across Linux nodes. Changes run nginx -t first.',
    'login.cardTitle': 'Sign in', 'login.cardDescription': 'Use the admin password set at install.',
    'login.password': 'Password', 'login.passwordPlaceholder': 'Admin password', 'login.submit': 'Sign in',
    'login.submitting': 'Checking…', 'login.secure': 'Only a short-lived session token is stored in this browser.',
    'login.tooShort': 'Password must be at least 12 characters.', 'login.invalid': 'Invalid password or controller offline.', 'login.configUnavailable': 'Login settings are temporarily unavailable.', 'login.challengeUnavailable': 'Security verification is temporarily unavailable.',
    'overview.title': 'Overview', 'overview.description': 'Nodes, domains, certificates, and recent changes.',
    'overview.nodesOnline': 'Nodes', 'overview.allNormal': 'All online', 'overview.checkNeeded': 'Issues',
    'overview.certRisk': 'Expiring', 'overview.within30': 'Within 30 days', 'overview.noRisk': 'No risk',
    'overview.routes': 'Domains', 'overview.searchDomain': 'Search domains', 'overview.noDomain': 'No domains',
    'overview.noDomainDescription': 'Add a route to see it here.', 'overview.adjustSearch': 'Try another keyword.',
    'overview.total': '{count} total', 'overview.viewAll': 'All', 'overview.timeline': 'Certificate expiry',
    'overview.next90': 'Next 90 days', 'overview.nodeHealth': 'Nodes', 'overview.activity': 'Activity', 'overview.pending': 'Pending',
    'overview.noActivity': 'No activity', 'overview.noActivityDescription': 'Deployments and renewals show up here.',
    'overview.noCertificates': 'No certificates', 'overview.noCertificatesDescription': 'Issue or upload a certificate first.',
    'overview.viewCertificates': 'Certs', 'overview.noNodes': 'No nodes', 'overview.noNodesDescription': 'Generate an install command for a VPS.',
    'overview.viewNodes': 'Nodes', 'overview.waitingReport': 'Awaiting report', 'overview.nginxUndetected': 'Not detected',
    'overview.nginxOk': 'Nginx OK', 'overview.nginxBad': 'Nginx issue',
    'overview.quickActions': 'Quick actions', 'overview.activeRoutes': 'Active domains', 'overview.autoRenewCerts': 'Auto-renew',
    'overview.expiringDomains': 'Expiry alerts', 'overview.commands': 'Install & uninstall',
    'overview.installNode': 'Install node', 'overview.uninstallNode': 'Uninstall node', 'overview.uninstallController': 'Uninstall controller',
    'overview.uninstallControllerWarning': 'Removes the controller and local agent. Existing Nginx configuration and certificates remain.',
    'domain.title': 'Domains', 'domain.description': 'Point domains at upstream host and port on a node.',
    'domain.add': 'Add', 'domain.editTitle': 'Edit domain', 'domain.updateSubmit': 'Save', 'domain.searchPlaceholder': 'Search domain or node', 'domain.managedTab': 'Managed',
    'domain.discoveredTab': 'Discovered', 'domain.discoveredTitle': 'Existing sites on nodes',
    'domain.discoveredDescription': 'Monitor only, or back up and take over the config.',
    'domain.adopt': 'Watch', 'domain.adopted': 'Managed', 'domain.noDiscovered': 'No new sites',
    'domain.noDiscoveredDescription': 'server_name entries sync on the next node heartbeat.',
    'domain.empty': 'No domains yet', 'domain.emptyDescription': 'New routes validate with nginx -t before reload.',
    'domain.columnDomain': 'Domain', 'domain.columnRoute': 'Upstream', 'domain.columnCert': 'Cert',
    'domain.columnNode': 'Node', 'domain.columnState': 'State', 'domain.localConfig': 'Watch only',
    'domain.takenOverBadge': 'Taken over', 'domain.managedConfig': 'Atlas', 'domain.configPath': 'Config', 'domain.tls': 'TLS', 'domain.http': 'HTTP',
    'domain.showing': '{shown}/{total}', 'domain.transactionNote': '',
    'domain.discoveredFooter': 'From nginx -T',
    'domain.removeTitle': 'Remove domain configuration?', 'domain.removeObservedTitle': 'Stop managing this domain?',
    'domain.removeDescription': 'The node will remove the managed configuration for {domain} and reload only after nginx -t succeeds. Certificate files remain.',
    'domain.removeObservedDescription': 'This removes {domain} only from Atlas. The node’s original Nginx configuration will not be changed.',
    'domain.removeTakenOverTitle': 'Stop takeover and restore the original rule?',
    'domain.removeTakenOverDescription': 'The node will remove the Atlas configuration for {domain}, restore the pre-takeover Nginx rule, and reload only after nginx -t passes. Certificates are preserved.',
    'domain.removeAction': 'Remove domain', 'domain.stopManaging': 'Stop managing', 'domain.restoreOriginal': 'Restore original rule',
    'domain.runtimeQueued': 'Queued', 'domain.runtimeRunning': 'Deploying', 'domain.runtimeFailed': 'Failed',
    'domain.runtimeActive': 'Running', 'domain.runtimePending': 'Pending', 'domain.unconnected': 'Unlinked',
    'domain.certPending': 'No cert', 'domain.httpOnlyShort': 'HTTP',
    'domain.drawerKicker': 'New route', 'domain.drawerSubtitle': '', 'domain.stepRoute': 'Route', 'domain.stepCertificate': 'Cert', 'domain.stepDeploy': 'Deploy',
    'domain.targetNode': 'Node', 'domain.upstreamHost': 'Upstream', 'domain.projectPort': 'Port', 'domain.certificateSource': 'Certificate',
    'domain.existingCertificate': 'Existing', 'domain.uploadCertificate': 'Upload', 'domain.letsencrypt': "Let's Encrypt", 'domain.letsencryptShort': 'ACME',
    'domain.certificateLocation': 'Certificate', 'domain.localCertificate': 'Node /etc/ssl/{domain}', 'domain.currentNodeCertificate': 'Current node certificate', 'domain.controllerCertificate': '{domain} · {days}d',
    'domain.syncOthers': 'Sync to other nodes', 'domain.noOtherNodes': 'No other nodes', 'domain.syncDescription': 'Push the certificate and reload selected nodes.',
    'domain.preview': 'Preview', 'domain.httpOnly': 'HTTP only for now',
    'domain.deployProof': '',
    'domain.offlineWarning': 'Node is offline; the job will wait.', 'domain.submit': 'Deploy',
    'domain.validation': 'Enter a valid domain, node, upstream host, and port.',
    'domain.validationFiles': 'Choose fullchain.pem and privkey.pem.', 'domain.validationAccounts': 'DNS and ACME accounts are required.',
    'certificate.title': 'Certificates', 'certificate.description': 'Issue, renew, and sync to nodes.',
    'certificate.add': 'Add', 'certificate.total': 'Certs', 'certificate.expiringCount': 'Expiring',
    'certificate.autoRenewCount': 'Auto-renew', 'certificate.nodeCopies': 'Copies', 'certificate.syncedNodes': 'Synced nodes',
    'certificate.searchPlaceholder': 'Search domain', 'certificate.allStatuses': 'All',
    'certificate.validOnly': 'Valid', 'certificate.expiringOnly': 'Expiring', 'certificate.empty': 'No certificates',
    'certificate.emptyDescription': 'Upload, issue via ACME, or import from a node.',
    'certificate.sourceACME': 'ACME', 'certificate.sourceUpload': 'Upload', 'certificate.sourceLocal': 'Node',
    'certificate.expiry': 'Expiry', 'certificate.source': 'Source', 'certificate.autoRenew': 'Auto-renew',
    'certificate.distribution': 'Copies', 'certificate.renew': 'Request', 'certificate.sync': 'Sync',
    'certificate.enabled': 'Auto-renew on', 'certificate.disabled': 'Auto-renew off', 'certificate.remaining': '{count}d',
    'certificate.enableAutoRenew': 'Enable auto-renew for {domain}', 'certificate.disableAutoRenew': 'Disable auto-renew for {domain}',
    'certificate.automationUnavailable': 'Configure a signing node and certificate account first.',
    'certificate.renewConfirmTitle': 'Request a new certificate?', 'certificate.renewConfirmDescription': '{domain} will request a new certificate through DNS-01, write it to the target node, and validate Nginx.', 'certificate.renewConfirmAction': 'Confirm request',
    'certificate.fingerprint': 'SHA-256 fingerprint', 'certificate.modeUpload': 'Upload certificate',
    'certificate.modeUploadShort': 'Upload', 'certificate.modeIssue': 'Issue certificate', 'certificate.modeIssueShort': 'Issue',
    'certificate.modeImport': 'Node certificate', 'certificate.modeImportShort': 'Node',
    'certificate.modeUploadHint': '', 'certificate.modeIssueHint': '',
    'certificate.modeImportHint': '', 'certificate.domain': 'Certificate domain',
    'certificate.signingNode': 'Signing node', 'certificate.sourceNode': 'Source node', 'certificate.nodeCertificate': 'Node certificate',
    'certificate.dnsAccount': 'DNS account', 'certificate.acmeAccount': 'ACME account',
    'certificate.syncNodes': 'Automatic distribution', 'certificate.syncHint': '',
    'certificate.renewToggle': 'Renew before expiry', 'certificate.renewHint': 'Run DNS-01 automatically inside the {days}-day expiry window.',
    'certificate.fullchain': 'Certificate file', 'certificate.privkey': 'Private key file', 'certificate.certificateFile': 'Certificate file', 'certificate.privateKeyFile': 'Private key file', 'certificate.chooseFile': 'Choose file', 'certificate.detectDomain': 'Detect domain and normalize storage automatically',
    'certificate.submitUpload': 'Validate and add', 'certificate.submitIssue': 'Issue certificate', 'certificate.submitImport': 'Import certificate',
    'certificate.noNodeCertificates': 'This node has not reported any valid certificates that can be imported.',
    'certificate.validationDomain': 'Enter a valid certificate domain.', 'certificate.validationFiles': 'Choose a certificate and private key file.',
    'certificate.validationNode': 'Select an available node.', 'certificate.validationAccounts': 'Select both a DNS account and an ACME account.',
    'nodes.title': 'Nodes', 'nodes.description': 'Agents dial out to the controller; no extra inbound ports.',
    'nodes.add': 'Add', 'nodes.empty': 'No nodes yet', 'nodes.emptyDescription': 'The install command is in Overview.',
    'nodes.command': 'Generate command', 'nodes.hostnamePending': 'Awaiting hostname', 'nodes.addresses': 'Addresses',
    'nodes.nginx': 'Nginx', 'nodes.platform': 'Platform', 'nodes.certDirectory': 'Certificate directory', 'nodes.certFound': '{count} discovered',
    'nodes.siteFound': '{count} domains', 'nodes.lastSeen': 'Last seen: {time}', 'nodes.never': 'Never connected',
    'nodes.revoke': 'Revoke node', 'nodes.revokeTitle': 'Revoke node access?',
    'nodes.revokeDescription': '{node} will no longer receive tasks. Existing Nginx configuration and certificates on the node will remain.',
    'accounts.title': 'Accounts', 'accounts.description': 'DNS and ACME credentials stay encrypted.',
    'accounts.dnsTitle': 'DNS accounts', 'accounts.acmeTitle': 'ACME accounts', 'accounts.addDNS': 'Add DNS account',
    'accounts.addACME': 'Add ACME account', 'accounts.emptyDNS': 'No DNS account configured', 'accounts.emptyDNSDescription': 'Add a lego-supported DNS provider with least-privilege API credentials.',
    'accounts.emptyACME': 'No ACME account configured', 'accounts.emptyACMEDescription': 'Store an email, directory URL, and optional EAB details.',
    'accounts.credentials': '{count} credentials', 'accounts.eab': 'EAB configured', 'accounts.standard': 'Standard account',
    'accounts.encrypted': 'AES-256-GCM encrypted', 'accounts.editDNS': 'Edit DNS account', 'accounts.editACME': 'Edit ACME account',
    'audit.title': 'Logs', 'audit.description': 'System events and operations.',
    'audit.event': 'Event', 'audit.target': 'Target', 'audit.time': 'Time', 'audit.level': 'Level', 'audit.controller': 'Controller',
    'audit.success': 'Success', 'audit.warning': 'Warning', 'audit.error': 'Error', 'audit.info': 'Info',
    'audit.empty': 'No audit events', 'audit.emptyDescription': 'Events will appear after the first configuration operation.',
    'pending.title': 'Pending', 'pending.description': '', 'pending.empty': 'Nothing needs attention',
    'pending.queued': 'Queued', 'pending.running': 'Running', 'pending.failed': 'Failed', 'pending.reason': 'Failure reason', 'pending.noReason': 'No failure reason returned', 'pending.retry': 'Retry',
    'pending.applyDomain': 'Deploy domain', 'pending.deleteDomain': 'Remove domain', 'pending.syncCertificate': 'Sync certificate', 'pending.issueCertificate': 'Request certificate',
    'pending.captureCertificate': 'Import certificate', 'pending.reloadNginx': 'Reload Nginx', 'pending.updateAtlas': 'Update Atlas', 'pending.updateSystem': 'Update system',
    'settings.title': 'Settings', 'settings.description': 'Accounts, node status, and access.',
    'settings.certificateAccounts': 'Certificate accounts', 'settings.cloudflareToken': 'Cloudflare API token', 'settings.acmeEmail': 'ACME email',
    'settings.configured': 'Configured', 'settings.notConfigured': 'Not configured', 'settings.nodeStatus': 'Node status',
    'settings.nodePollFrequency': 'Refresh interval', 'settings.seconds': '{count} seconds',
    'settings.appearance': 'Appearance & language', 'settings.theme': 'Color mode', 'settings.language': 'Interface language',
    'settings.security': 'Certificate security', 'settings.securityDescription': '',
    'settings.transport': 'Node communication', 'settings.transportDescription': '',
    'settings.transaction': 'Nginx transaction', 'settings.transactionDescription': '',
    'settings.atomic': 'Atomic rollback', 'settings.password': 'Administrator password', 'settings.passwordDescription': '',
    'settings.changePassword': 'Change password', 'settings.logout': 'Sign out of this administrator session',
    'settings.accessProtection': 'Access protection', 'settings.enabled': 'Enabled', 'settings.disabled': 'Disabled',
    'settings.ipAllowlist': 'Panel IP allowlist', 'settings.ruleCount': '{count} rules', 'settings.currentIP': 'Current IP: {ip}',
    'settings.keepSecret': 'Keep current secret', 'settings.turnstileCredentialsRequired': 'Enter the Site Key and Secret Key.',
    'dialog.nodeTitle': 'Add Linux node', 'dialog.nodeDescription': 'The hostname is used automatically during enrollment.',
    'dialog.nodeName': 'Node name', 'dialog.nodeNamePlaceholder': 'nanami-sakura', 'dialog.generate': 'Generate command',
    'dialog.commandReady': 'Node command is ready', 'dialog.copyCommand': 'Copy command', 'dialog.copied': 'Copied',
    'dialog.commandHint': 'The command contains a short-lived enrollment token. Do not paste it into public logs.',
    'dialog.dnsAddTitle': 'Add DNS account', 'dialog.dnsEditTitle': 'Edit DNS account',
    'dialog.dnsDescription': 'Use a least-privilege Zone DNS edit token.',
    'dialog.accountName': 'Account name', 'dialog.provider': 'lego provider', 'dialog.credentials': 'Environment credentials',
    'dialog.addCredential': 'Add', 'dialog.keepCredentials': 'Keep current encrypted credentials', 'dialog.replaceCredentials': 'Replace credentials',
    'dialog.credentialName': 'Credential variable {index}', 'dialog.credentialValue': 'Credential value {index}', 'dialog.removeCredential': 'Remove this credential',
    'dialog.credentialHint': 'API responses return variable names only; secret values never return to the browser.',
    'dialog.acmeAddTitle': 'Add ACME account', 'dialog.acmeEditTitle': 'Edit ACME account',
    'dialog.acmeDescription': '',
    'dialog.email': 'Contact email', 'dialog.directory': 'ACME directory', 'dialog.eab': 'External Account Binding (EAB)',
    'dialog.keepEAB': 'Keep existing EAB secret', 'dialog.clearEAB': 'Clear EAB', 'dialog.eabKID': 'EAB KID', 'dialog.eabHMAC': 'EAB HMAC',
    'dialog.syncTitle': 'Sync certificate', 'dialog.syncDescription': 'Push the current {domain} certificate safely to other nodes.',
    'dialog.syncOnline': 'Online; task will be picked up immediately', 'dialog.syncOffline': 'Offline; task will remain queued',
    'dialog.syncProof': '',
    'dialog.syncAction': 'Sync to {count} nodes', 'dialog.passwordTitle': 'Change administrator password',
    'dialog.passwordDescription': 'Other sessions are revoked immediately; this browser receives a replacement session automatically.',
    'dialog.currentPassword': 'Current password', 'dialog.newPassword': 'New password', 'dialog.confirmPassword': 'Confirm new password',
    'dialog.passwordRule': 'At least 12 characters. A password manager is recommended.', 'dialog.passwordMismatch': 'The new passwords do not match.',
    'dialog.changePassword': 'Change password', 'dialog.remove': 'Remove',
    'settings.quickPreferences': 'Appearance & language',
    'domain.routeHint': '', 'domain.certificateHint': '',
    'domain.validationCertificate': 'Select an existing certificate that covers this domain.', 'domain.validationCloudflare': 'Select a Cloudflare account with Zone DNS edit access.',
    'domain.noMatchingCertificate': 'No certificate covers this domain', 'domain.cloudflareTitle': 'Sync Cloudflare DNS',
    'domain.cloudflareHint': '', 'domain.cloudflareAccount': 'Cloudflare account',
    'domain.recordContent': 'Record content', 'domain.recordAuto': 'Use node IP automatically', 'domain.proxyMode': 'Proxy status',
    'domain.orangeCloud': 'Proxied', 'domain.grayCloud': 'DNS only', 'domain.observe': 'Watch', 'domain.takeover': 'Take over',
    'domain.takeoverUnavailable': 'Needs a usable upstream, supported config path, and a covering certificate for TLS.',
    'domain.nginxSettings': 'Nginx settings', 'domain.nginxSettingsHint': '',
    'domain.nginxWebsocket': 'WebSocket support', 'domain.nginxWebsocketHint': '',
    'domain.nginxHttp2': 'HTTP/2 protocol', 'domain.nginxHttp2Hint': '',
    'domain.nginxGzip': 'Gzip compression', 'domain.nginxGzipHint': '',
    'domain.takeoverConfirmTitle': 'Take over this site?', 'domain.takeoverConfirmDescription': 'Backs up {path}, then writes Atlas config for {domain}. Rolls back if nginx -t fails.',
    'domain.takeoverConfirmAction': 'Take over',
    'certificate.additionalNames': 'Certificate names', 'certificate.additionalNamesHint': 'Press Enter or comma to add a name. Wildcards such as *.example.com are supported; limit 20.',
    'certificate.validationAutomation': 'Choose a signing node and a renewal window from 7 to 60 days.',
    'certificate.editAutomation': 'Edit issuance & renewal', 'certificate.editAutomationHint': '',
    'certificate.renewDays': 'Renew before expiry (days)', 'certificate.namesCount': '{count} names',
    'nodes.manage': 'Manage', 'nodes.manageTitle': '{node}', 'nodes.manageDescription': 'Name, release, and package updates.',
    'nodes.controller': 'Controller', 'nodes.manageControllerDescription': 'Updates controller and local agent, then restarts services.',
    'nodes.rename': 'Node display name', 'nodes.atlasRelease': 'Nginx Atlas release', 'nodes.controllerRelease': 'Controller & local agent', 'nodes.versionPair': 'Current {current} · latest {latest}',
    'nodes.checkUpdate': 'Check update', 'nodes.updateAvailable': 'Update to {version}', 'nodes.upToDate': 'Latest release installed',
    'nodes.updateAtlas': 'Update Atlas', 'nodes.confirmUpdate': 'Confirm update', 'nodes.systemUpdate': 'APT & Nginx update',
    'nodes.systemUpdateHint': 'Runs apt update / upgrade, preserves current config, then validates and reloads Nginx.', 'nodes.systemUpdateUnsupported': 'Only APT-based nodes are currently supported.',
    'nodes.updatePackages': 'Update packages', 'nodes.confirmSystemUpdate': 'Confirm system update', 'nodes.uninstallTitle': 'Uninstall node agent',
    'nodes.uninstallHint': 'This command removes only the project node agent; Nginx, site rules, and /etc/ssl certificates remain.', 'nodes.copyUninstall': 'Copy uninstall command',
    'nodes.reinstallTitle': 'Re-obtain Install Command', 'nodes.reinstallHint': 'Run this command on the target Linux VPS to enroll or re-enroll with this controller.',
    'nodes.generateInstallCommand': 'Get Install Command', 'nodes.copyInstall': 'Copy Install Command',
    'toast.domainQueued': 'Domain queued for deployment; the node will validate Nginx first.',
    'toast.domainObserved': 'Existing node domain added to management; its original Nginx configuration was not modified.', 'toast.domainRemoved': 'Domain removal task queued.',
    'toast.observationRemoved': 'Stopped managing the existing node domain; its original configuration was not modified.', 'toast.nodeRevoked': 'Node credentials revoked.',
    'toast.dnsSaved': 'DNS account saved securely.', 'toast.acmeSaved': 'ACME account saved.',
    'toast.certQueued': 'Certificate task queued.', 'toast.certUploaded': 'Certificate validated and added to management.',
    'toast.renewQueued': '{domain} queued for certificate issuance.', 'toast.autoRenewEnabled': 'Auto-renew enabled for {domain}.', 'toast.autoRenewDisabled': 'Auto-renew disabled for {domain}.', 'toast.syncQueued': 'Certificate queued for synchronization to {count} nodes.',
    'toast.passwordChanged': 'Administrator password changed; other sessions were revoked.',
    'toast.domainTakeoverQueued': 'Existing Nginx rule queued for safe takeover.', 'toast.certificateAutomationSaved': 'Certificate issuance and renewal settings saved.',
    'toast.releaseChecked': 'Latest GitHub release checked.', 'toast.nodeRenamed': 'Node name updated.',
    'toast.atlasUpdateQueued': 'Atlas update queued on the node.', 'toast.systemUpdateQueued': 'APT and Nginx update queued on the node.',
    'toast.pollFrequencySaved': 'Node status interval updated.', 'toast.accessSettingsSaved': 'Access protection saved.', 'toast.jobRetried': 'Task queued again.',
    'error.dashboard': 'Unable to load controller status', 'error.domain': 'Unable to create domain', 'error.adopt': 'Unable to adopt node domain',
    'error.node': 'Unable to generate node command', 'error.dns': 'Unable to save DNS account', 'error.acme': 'Unable to save ACME account',
    'error.certificate': 'Unable to create certificate task', 'error.password': 'Unable to change administrator password',
    'error.removeDomain': 'Unable to remove domain', 'error.revokeNode': 'Unable to revoke node', 'error.renew': 'Unable to create renewal task', 'error.autoRenew': 'Unable to change auto-renew', 'error.sync': 'Unable to create sync task',
    'error.takeover': 'Unable to take over the existing Nginx rule', 'error.certificateAutomation': 'Unable to save certificate automation settings',
    'error.release': 'Unable to check the GitHub release', 'error.uninstallCommand': 'Unable to generate uninstall command', 'error.renameNode': 'Unable to rename node',
    'error.atlasUpdate': 'Unable to queue the Atlas update', 'error.systemUpdate': 'Unable to queue the system update', 'error.settings': 'Unable to save settings', 'error.retryJob': 'Unable to retry task',
    'update.kicker': 'Controller update', 'update.title': 'Updating', 'update.complete': 'Update complete', 'update.failed': 'Update failed',
    'update.prepare': 'Prepare', 'update.install': 'Install', 'update.restart': 'Restart', 'update.refreshing': 'Refreshing the page…',
  },
}

const PreferencesContext = createContext<PreferencesValue | null>(null)
const themeKey = 'nginx-atlas-theme'
const languageKey = 'nginx-atlas-language'

function readPreference<T extends string>(key: string, allowed: readonly T[], fallback: T): T {
  try {
    const value = localStorage.getItem(key) as T | null
    return value && allowed.includes(value) ? value : fallback
  } catch {
    return fallback
  }
}

function systemLanguage(): EffectiveLanguage {
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en'
}

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<ThemeMode>(() => readPreference(themeKey, ['system', 'light', 'dark'], 'system'))
  const [language, setLanguageState] = useState<LanguageMode>(() => readPreference(languageKey, ['system', 'zh', 'en'], 'system'))
  const [systemDark, setSystemDark] = useState(() => window.matchMedia('(prefers-color-scheme: dark)').matches)
  const [detectedLanguage, setDetectedLanguage] = useState<EffectiveLanguage>(systemLanguage)

  useEffect(() => {
    const media = window.matchMedia('(prefers-color-scheme: dark)')
    const update = () => setSystemDark(media.matches)
    media.addEventListener('change', update)
    return () => media.removeEventListener('change', update)
  }, [])

  useEffect(() => {
    const update = () => setDetectedLanguage(systemLanguage())
    window.addEventListener('languagechange', update)
    return () => window.removeEventListener('languagechange', update)
  }, [])

  const effectiveTheme = theme === 'system' ? (systemDark ? 'dark' : 'light') : theme
  const effectiveLanguage = language === 'system' ? detectedLanguage : language
  const locale = effectiveLanguage === 'zh' ? 'zh-CN' : 'en-US'

  useEffect(() => {
    document.documentElement.dataset.theme = effectiveTheme
    document.documentElement.lang = effectiveLanguage === 'zh' ? 'zh-CN' : 'en'
    document.documentElement.style.colorScheme = effectiveTheme
  }, [effectiveTheme, effectiveLanguage])

  const setTheme = useCallback((value: ThemeMode) => {
    setThemeState(value)
    try { localStorage.setItem(themeKey, value) } catch { /* Preference remains active for this page. */ }
  }, [])

  const setLanguage = useCallback((value: LanguageMode) => {
    setLanguageState(value)
    try { localStorage.setItem(languageKey, value) } catch { /* Preference remains active for this page. */ }
  }, [])

  const t = useCallback((key: string, variables: Variables = {}) => {
    const template = messages[effectiveLanguage][key] ?? messages.zh[key] ?? key
    return Object.entries(variables).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)), template)
  }, [effectiveLanguage])

  const value = useMemo<PreferencesValue>(() => ({
    theme, effectiveTheme, language, effectiveLanguage, locale, setTheme, setLanguage, t,
  }), [theme, effectiveTheme, language, effectiveLanguage, locale, setTheme, setLanguage, t])

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>
}

export function usePreferences(): PreferencesValue {
  const value = useContext(PreferencesContext)
  if (!value) throw new Error('usePreferences must be used inside PreferencesProvider')
  return value
}
